### ISSUE TITLE
WARNING: Normalized tree is growing past 200000 elements. Aborting normalization.  

### ISSUE THREAD

**Issue by jess-sheneberger** [andimoto/keebcu#10]
This project is AWESOME!

I'm on the "develop" branch, using OpenSCAD 2021.01 on Mac OS 12.5.  I'm trying to run mainCaseLeft() on andimoto6061, andimoto7583, and andimoto6064. These all give me the following messages in the console:

WARNING: Normalized tree is growing past 200000 elements. Aborting normalization.  
WARNING: CSG normalization resulted in an empty tree 
Normalized tree has 0 elements!
Compile and preview finished.

I've messed around a bunch trying to figure out why and where this is happening, but I've had no luck so far. I can try it on Linux but I'm not sure that's my problem.

Any ideas?

**Comment by jess-sheneberger** [comment]
I messed around with this some more and I think I've got it fixed.  Take a look @andimoto and let me know what you think. I'm very new to OpenSCAD so my change might have broken something else.

**Comment by andimoto** [comment]
Thanks again Jess. Usually I just hit Render and after some seconds I got a model of the left case. So I don't check the preview.  But your solution is very nice.
I will check that with some other models just to be sure. But thats an very simple solution. I like that.
